### PR TITLE
Patch husky : Use different package managers

### LINKED ISSUE #84: Husky disallows using another package manager than npm
❌ Problem : If you try to use another package manager than npm (pnpm/yarn/...) the new rules of husky generate an error and blocks the current commit.

⚡️ Potential fix : Add rule to ignore pnpm-lock.yaml, yarn-lock and maybe package-lock.json

### PR DESCRIPTION
**Pull request by ioayoub**
Add: yarn.lock in the root folder
Add: pnpm-lock.yaml in the root folder
Update: Readme.md reminder ‘Before you start’
Update: husky/pre-commit to ignore package.json 
Closes #84

### CODE REVIEW

**Comment by rocambille** [comment]
perfect :)

now I see it, may be we should also provide lock files in frontend and backend directories ?

**Comment by ioayoub** [comment]
Nice :)
frontend and backend directories are already ignored, isn't that enough ? 
Unless you have an idea behind this ? 🤔

**Comment by rocambille** [comment]
No big ideas : my concern here is not related to the original issue. It is to provide lock files to ensure the exact tree of dependencies will be downloaded on install. Like I said, we should have generated these files for pnpm and yarn from the start like the package-lock.json files :sweat_smile: 

Do you think it's useless ?

(By the way, I took the liberty to add a commit in your branch to fix a typo in the README, and to update the CHANGELOG :wink: )

**Comment by ioayoub** [comment]
Yep, i'm ok it's way better to add these files in the frontend and backend directories to secure the installation tree (to avoid headaches also 😅).
I'll add them for both directories in this PR.
The last thing we need to do in finding a way to dismiss the warnings related to different lock files.

**Comment by rocambille** [comment]
Which warnings ? I can't see them :open_mouth:

**Comment by ioayoub** [comment]
image

Displayed on installations, nothing to fear just a warning. 
Edit : Seems like pnpm doesn't generate them (to confirm).

Edit2: PR updated with the lock files in frontend/backend directories. Waiting for your review before merging ;)

**Review by rocambille — APPROVED** [review]

**Pull request merged**
